[package]
name = "downloadSongs"
version = "0.1.0"
edition = "2024"

[dependencies]
audiotags = "0.5.0"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde_json = "1.0.140"
yt-dlp = "1.3.2"
